name: "Build Lint Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v0.0.15
    secrets: inherit
    with:
      platforms: "linux/amd64"
      webTarget: hyku-base
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.15
    with:
      setup_db_cmd: bundle exec rake prepare_and_run_tests
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.15
